server:
  port: 7001
  servlet:
    context-path: /starling/savings-app
spring:
  banner:
    location: banner.txt
  liquibase.changeLog: classpath:db/changelog/changelog.yml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:starling-savings-goal-db
    username: starling-saving-goal
    password: starling-saving-goal
    platform: h2
  jpa:
    hibernate.ddl-auto: update

starling.api.base.url: https://api-sandbox.starlingbank.com/api/v2